TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    zlibrary/ui/src/qml/application/ZLQmlApplicationWindow.cpp \
    zlibrary/ui/src/qml/library/ZLibrary.cpp \
    zlibrary/ui/src/qml/view/ZLQmlNetworkAccessFactory.cpp \
    zlibrary/ui/src/qml/view/ZLQmlPaintContext.cpp \
    zlibrary/ui/src/qml/view/ZLQmlTreeImageProvider.cpp \
    zlibrary/ui/src/qml/view/ZLQmlViewWidget.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialogManager.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialog.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialogContent.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlFileSystemModel.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlOpenFileDialog.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlOptionsDialog.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlOptionView.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlProgressDialog.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlQuestionDialog.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQmlTree.cpp \
    zlibrary/ui/src/qml/dialogs/ZLQtUtil.cpp \
    zlibrary/ui/src/qml/filesystem/ZLQtFSManager.cpp \
    zlibrary/ui/src/qml/image/ZLQtImageManager.cpp \
    zlibrary/ui/src/qml/network/ZLQtNetworkManager.cpp \
    zlibrary/ui/src/qml/time/ZLQtTime.cpp \
    zlibrary/ui/src/qml/util/ZLQtKeyUtil.cpp \
    fbreader/src/fbreader/FBReader.cpp

OTHER_FILES += \
    zlibrary/ui/src/qml/declarative/sailfish/CoverPage.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogBooleanView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogChoiceView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogColorView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogComboView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogContent.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogEditableComboView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogMultilineView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogPathView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogSpinView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogStaticView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/DialogStringView.qml \
    zlibrary/ui/src/qml/declarative/sailfish/Main.qml \
    zlibrary/ui/src/qml/declarative/sailfish/MainPage.qml \
    zlibrary/ui/src/qml/declarative/sailfish/MessageDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/OptionsDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/ProgressDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/QuestionDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/SimpleDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/TreeDialogItemPage.qml \
    zlibrary/ui/src/qml/declarative/sailfish/TreeDialogPage.qml \
    zlibrary/ui/src/qml/declarative/sailfish/YesNoDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/CoverPage.png \
    zlibrary/ui/libzlui-qml.a \
    zlibrary/ui/src/qml/declarative/sailfish/OpenFileDialog.qml \
    zlibrary/ui/src/qml/declarative/sailfish/ContextMenu.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/DatePicker.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/FastScrollAnimation.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/HintReferenceCounter.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/RemorseItem.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/RemorsePopup.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/TextAutoScroller.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/Util.js \
    zlibrary/ui/src/qml/declarative/sailfish/private/BoundsBehavior.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/DateGrid.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/DefaultCover.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/FastScrollAnimation.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/HighlightBar.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/HighlightImage.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/MenuIndicator.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/PageEdgeTransition.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/PageHeaderDescription.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/PageStackIndicator.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/PulleyMenuBase.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/QuickScroll.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/QuickScrollArea.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/QuickScrollButton.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/ReturnToHomeHint.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/SliderValueLabel.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/TextAutoScroller.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/TextBase.qml \
    zlibrary/ui/src/qml/declarative/sailfish/private/YearMonthMenu.qml

HEADERS += \
    zlibrary/ui/src/qml/application/ZLQmlApplicationWindow.h \
    zlibrary/ui/src/qml/view/ZLQmlNetworkAccessFactory.h \
    zlibrary/ui/src/qml/view/ZLQmlPaintContext.h \
    zlibrary/ui/src/qml/view/ZLQmlTreeImageProvider.h \
    zlibrary/ui/src/qml/view/ZLQmlViewWidget.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialogManager.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialog.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlDialogContent.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlFileSystemModel.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlOpenFileDialog.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlOptionsDialog.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlOptionView.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlProgressDialog.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlQuestionDialog.h \
    zlibrary/ui/src/qml/dialogs/ZLQmlTree.h \
    zlibrary/ui/src/qml/dialogs/ZLQtUtil.h \
    zlibrary/ui/src/qml/filesystem/ZLQtFSManager.h \
    zlibrary/ui/src/qml/image/ZLQtImageManager.h \
    zlibrary/ui/src/qml/network/ZLQtNetworkManager.h \
    zlibrary/ui/src/qml/time/ZLQtTime.h \
    zlibrary/ui/src/qml/util/ZLQtKeyUtil.h \
    zlibrary/text/include/ZLTextAlignmentType.h \
    zlibrary/text/include/ZLTextArea.h \
    zlibrary/text/include/ZLTextAreaController.h \
    zlibrary/text/include/ZLTextElement.h \
    zlibrary/text/include/ZLTextFontModifier.h \
    zlibrary/text/include/ZLTextHyphenator.h \
    zlibrary/text/include/ZLTextKind.h \
    zlibrary/text/include/ZLTextMark.h \
    zlibrary/text/include/ZLTextModel.h \
    zlibrary/text/include/ZLTextParagraph.h \
    zlibrary/text/include/ZLTextParagraphCursor.h \
    zlibrary/text/include/ZLTextPositionIndicator.h \
    zlibrary/text/include/ZLTextPositionIndicatorInfo.h \
    zlibrary/text/include/ZLTextRectangle.h \
    zlibrary/text/include/ZLTextRowMemoryAllocator.h \
    zlibrary/text/include/ZLTextSelectionModel.h \
    zlibrary/text/include/ZLTextStyle.h \
    zlibrary/text/include/ZLTextStyleCollection.h \
    zlibrary/text/include/ZLTextStyleOptions.h \
    zlibrary/text/include/ZLTextTeXHyphenator.h \
    zlibrary/text/include/ZLTextView.h \
    zlibrary/text/include/ZLTextWord.h \
    zlibrary/core/include/optionEntries/ZLColorOptionBuilder.h \
    zlibrary/core/include/optionEntries/ZLFontFamilyOptionEntry.h \
    zlibrary/core/include/optionEntries/ZLLanguageOptionEntry.h \
    zlibrary/core/include/optionEntries/ZLSimpleKeyOptionEntry.h \
    zlibrary/core/include/optionEntries/ZLSimpleOptionEntry.h \
    zlibrary/core/include/optionEntries/ZLStringEditOptionEntry.h \
    zlibrary/core/include/optionEntries/ZLStringInfoEntry.h \
    zlibrary/core/include/optionEntries/ZLToggleBooleanOptionEntry.h \
    zlibrary/core/include/allocator.h \
    zlibrary/core/include/shared_ptr.h \
    zlibrary/core/include/ZLApplication.h \
    zlibrary/core/include/ZLAsynchronousInputStream.h \
    zlibrary/core/include/ZLBase64EncodedImage.h \
    zlibrary/core/include/ZLBlockTreeNode.h \
    zlibrary/core/include/ZLBlockTreeView.h \
    zlibrary/core/include/ZLBoolean3.h \
    zlibrary/core/include/ZLColor.h \
    zlibrary/core/include/ZLDialog.h \
    zlibrary/core/include/ZLDialogContent.h \
    zlibrary/core/include/ZLDialogManager.h \
    zlibrary/core/include/ZLDir.h \
    zlibrary/core/include/ZLEncodingConverter.h \
    zlibrary/core/include/ZLExecutionData.h \
    zlibrary/core/include/ZLFile.h \
    zlibrary/core/include/ZLFileImage.h \
    zlibrary/core/include/ZLFileInfo.h \
    zlibrary/core/include/ZLFileUtil.h \
    zlibrary/core/include/ZLFSWatcher.h \
    zlibrary/core/include/ZLibrary.h \
    zlibrary/core/include/ZLImage.h \
    zlibrary/core/include/ZLImageManager.h \
    zlibrary/core/include/ZLInputStream.h \
    zlibrary/core/include/ZLKeyBindings.h \
    zlibrary/core/include/ZLLanguageDetector.h \
    zlibrary/core/include/ZLLanguageList.h \
    zlibrary/core/include/ZLLanguageUtil.h \
    zlibrary/core/include/ZLLogger.h \
    zlibrary/core/include/ZLMessage.h \
    zlibrary/core/include/ZLMimeType.h \
    zlibrary/core/include/ZLMirroredPaintContext.h \
    zlibrary/core/include/ZLNetworkImage.h \
    zlibrary/core/include/ZLNetworkManager.h \
    zlibrary/core/include/ZLNetworkRequest.h \
    zlibrary/core/include/ZLNetworkSSLCertificate.h \
    zlibrary/core/include/ZLNetworkUtil.h \
    zlibrary/core/include/ZLOpenFileDialog.h \
    zlibrary/core/include/ZLOptionEntry.h \
    zlibrary/core/include/ZLOptions.h \
    zlibrary/core/include/ZLOptionsDialog.h \
    zlibrary/core/include/ZLOutputStream.h \
    zlibrary/core/include/ZLPaintContext.h \
    zlibrary/core/include/ZLPlainAsynchronousInputStream.h \
    zlibrary/core/include/ZLPopupData.h \
    zlibrary/core/include/ZLProgressDialog.h \
    zlibrary/core/include/ZLResource.h \
    zlibrary/core/include/ZLRunnable.h \
    zlibrary/core/include/ZLSearchUtil.h \
    zlibrary/core/include/ZLStreamImage.h \
    zlibrary/core/include/ZLStringUtil.h \
    zlibrary/core/include/ZLTime.h \
    zlibrary/core/include/ZLTimeManager.h \
    zlibrary/core/include/ZLTreeActionNode.h \
    zlibrary/core/include/ZLTreeDialog.h \
    zlibrary/core/include/ZLTreeListener.h \
    zlibrary/core/include/ZLTreeNode.h \
    zlibrary/core/include/ZLTreePageNode.h \
    zlibrary/core/include/ZLTreeTitledNode.h \
    zlibrary/core/include/ZLTypeId.h \
    zlibrary/core/include/ZLUnicodeUtil.h \
    zlibrary/core/include/ZLUserData.h \
    zlibrary/core/include/ZLView.h \
    zlibrary/core/include/ZLXMLNamespace.h \
    zlibrary/core/include/ZLXMLReader.h \
    zlibrary/core/include/ZLXMLWriter.h \
    zlibrary/core/include/ZLZDecompressor.h

